import React from "react";
import { Link, NavLink } from "react-router";
import { Moon, Sun } from "lucide-react";

const links = [["/", "Dashboard"], ["/employees", "Employees"], ["/evaluations", "Evaluations"], ["/clients", "Clients"], ["/departments", "Departments"], ["/audit", "Audit logs"]];

export default function Page({ title, children }: { title: string; children?: React.ReactNode }) {
  const [dark, setDark] = React.useState(false);
  React.useEffect(() => {
    const saved = localStorage.getItem("pes_theme");
    const enabled = saved ? saved === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches;
    setDark(enabled);
    document.documentElement.classList.toggle("dark", enabled);
  }, []);
  const toggleTheme = () => { const enabled = !dark; setDark(enabled); localStorage.setItem("pes_theme", enabled ? "dark" : "light"); document.documentElement.classList.toggle("dark", enabled); };
  return <div className="min-h-screen bg-slate-50 text-slate-900 transition-colors dark:bg-slate-950 dark:text-slate-100"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r bg-white p-6 dark:border-slate-800 dark:bg-slate-900 md:block"><Link to="/" className="text-xl font-bold text-indigo-700">PES</Link><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Performance Evaluation System</p><nav className="mt-10 space-y-1">{links.map(([href, label]) => <NavLink key={href} to={href} className={({ isActive }) => `block rounded-lg px-3 py-2 text-sm ${isActive ? "bg-indigo-50 font-semibold text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300" : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}>{label}</NavLink>)}</nav><button onClick={toggleTheme} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} title={dark ? "Switch to light mode" : "Switch to dark mode"} className="absolute bottom-20 left-6 right-6 flex items-center justify-between rounded-lg border bg-slate-50 p-3 text-left text-xs text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700"><span>{dark ? "Light mode" : "Dark mode"}</span>{dark ? <Sun size={18} aria-hidden="true" /> : <Moon size={18} aria-hidden="true" />}</button><button onClick={() => { localStorage.removeItem("pes_access_token"); window.location.href = "/login"; }} className="absolute bottom-6 left-6 right-6 rounded-lg bg-slate-50 p-3 text-left text-xs text-slate-500 hover:bg-slate-100 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700">Sign out<br /><strong className="text-slate-700 dark:text-slate-200">Current account</strong></button></aside><main className="md:ml-64"><header className="flex items-center justify-between border-b bg-white px-6 py-5 dark:border-slate-800 dark:bg-slate-900 md:px-10"><div><p className="text-sm text-slate-500 dark:text-slate-400">Performance Evaluation System</p><h1 className="text-2xl font-bold">{title}</h1></div><button onClick={toggleTheme} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} title={dark ? "Switch to light mode" : "Switch to dark mode"} className="rounded-lg border p-2 text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800 md:hidden">{dark ? <Sun size={20} aria-hidden="true" /> : <Moon size={20} aria-hidden="true" />}</button></header><div className="p-6 md:p-10">{children ?? <p className="text-slate-500">No records yet.</p>}</div></main></div>;
}
