import { useEffect, useState } from "react";
import { Link, useParams } from "react-router";
import Page from "./_Page";

export default function EvaluationDetail() {
  const { id } = useParams();
  const [evaluation, setEvaluation] = useState<any>(null);
  const [error, setError] = useState("");
  useEffect(() => { const token = localStorage.getItem("pes_access_token"); fetch(`/api/evaluations/${id}`, { headers: { Authorization: `Bearer ${token}` } }).then(async response => { const value = await response.json().catch(() => ({})); if (!response.ok) throw new Error(value.error || "Unable to load evaluation."); setEvaluation(value.evaluation); }).catch(reason => setError(reason.message || "Unable to load evaluation.")); }, [id]);
  if (error) return <Page title="Evaluation detail"><p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p></Page>;
  if (!evaluation) return <Page title="Evaluation detail"><p className="text-sm text-slate-500">Loading evaluation…</p></Page>;
  const form = evaluation.form_config || { criteria: ["Communication", "Quality of work", "Responsiveness", "Professionalism"], instructions: "" };
  const publicUrl = evaluation.public_token ? `${window.location.origin}/evaluation/${evaluation.public_token}` : "";
  return <Page title="Evaluation detail"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/evaluations" className="text-sm text-slate-500 hover:underline">← Evaluations</Link><h2 className="mt-3 text-3xl font-semibold tracking-tight">{evaluation.employees?.name || `Employee #${evaluation.employee_id}`}</h2><p className="mt-1 text-sm text-slate-500">{evaluation.period}</p></div><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-semibold capitalize text-indigo-700">{evaluation.status}</span></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="font-semibold">Configured client form</h3><p className="mt-1 text-sm text-slate-500">{form.instructions}</p><div className="mt-5 space-y-2">{(form.criteria || []).map((criterion: string, index: number) => <div key={criterion} className="rounded-lg bg-slate-50 px-4 py-3 text-sm"><span className="mr-2 text-slate-400">{index + 1}.</span>{criterion}</div>)}</div></section><aside className="space-y-6"><section className="rounded-xl border bg-slate-900 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-indigo-300">Share with client</p><p className="mt-3 text-sm leading-6 text-slate-300">Send this link to the client. They do not need an account.</p>{publicUrl && <><input readOnly value={publicUrl} className="mt-4 w-full rounded-lg border-0 bg-slate-800 p-3 text-xs text-slate-200" /><div className="mt-3 flex gap-2"><a href={publicUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-900">Preview</a><button type="button" onClick={() => navigator.clipboard?.writeText(publicUrl)} className="rounded-lg bg-indigo-500 px-3 py-2 text-xs font-semibold text-white">Copy link</button></div></>}</section><section className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="font-semibold">Client submission</h3>{evaluation.client_score == null ? <p className="mt-3 text-sm text-slate-500">Waiting for the client to submit.</p> : <div className="mt-4 space-y-3 text-sm"><p>Score: <strong>{evaluation.client_score}/100</strong></p><p>Reference grade: <strong>{evaluation.client_grade}</strong></p><p>Requested increase: <strong>{evaluation.client_pct}%</strong></p>{evaluation.client_comments && <p className="rounded-lg bg-slate-50 p-3 text-slate-600">{evaluation.client_comments}</p>}</div>}</section></aside></div></div></Page>;
}
