import { useEffect, useState } from "react";
import { useParams } from "react-router";

function grade(score: number) { return score >= 90 ? "A" : score >= 80 ? "B" : score >= 70 ? "C" : score >= 60 ? "D" : "F"; }

export default function PublicEvaluation() {
  const { token } = useParams();
  const [evaluation, setEvaluation] = useState<any>(null);
  const [scores, setScores] = useState<Record<string, number>>({});
  const [increase, setIncrease] = useState(5);
  const [comments, setComments] = useState("");
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { fetch(`/api/public-evaluations/${token}`).then(async response => { const value = await response.json().catch(() => ({})); if (!response.ok) throw new Error(value.error || "This evaluation link is unavailable."); setEvaluation(value.evaluation); const criteria = value.evaluation?.form_config?.criteria || ["Overall performance"]; setScores(Object.fromEntries(criteria.map((criterion: string) => [criterion, 80]))); if (value.evaluation?.status !== "draft") setSubmitted(true); }).catch(reason => setError(reason.message || "This evaluation link is unavailable.")).finally(() => setLoading(false)); }, [token]);
  const criteria: string[] = evaluation?.form_config?.criteria || ["Overall performance"];
  const average = Math.round(Object.values(scores).reduce((sum, value) => sum + value, 0) / Math.max(criteria.length, 1));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setSubmitting(true); try { const response = await fetch(`/api/public-evaluations/${token}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_score: average, client_scores: scores, client_pct: increase, client_comments: comments }) }); const value = await response.json().catch(() => ({})); if (!response.ok) throw new Error(value.error || "Unable to submit evaluation."); setSubmitted(true); } catch (reason: any) { setError(reason.message || "Unable to submit evaluation."); } finally { setSubmitting(false); } };
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-slate-50 text-sm text-slate-500">Loading evaluation…</main>;
  if (error && !evaluation) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-xl border bg-white p-8 text-center"><h1 className="text-xl font-semibold">Evaluation unavailable</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></main>;
  if (submitted) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700">✓</div><h1 className="mt-5 text-xl font-semibold">Thank you</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your evaluation has been submitted and locked. The employee’s manager will review it next.</p></div></main>;
  return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900"><div className="mx-auto max-w-xl"><div className="mb-6"><p className="text-sm font-semibold tracking-wide text-indigo-700">PES · Client evaluation</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Performance evaluation</h1><p className="mt-2 text-sm leading-6 text-slate-500">{evaluation?.form_config?.instructions || "Please score the employee based on your direct experience."}</p></div><form onSubmit={submit} className="rounded-xl border bg-white p-6 shadow-sm"><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Employee</p><p className="mt-1 font-semibold">{evaluation?.public_employee_name || "Assigned employee"}</p><p className="mt-1 text-sm text-slate-500">Period: {evaluation?.period}</p></div><div className="mt-7 space-y-5">{criteria.map(criterion => <label key={criterion} className="block text-sm font-medium"><div className="flex justify-between gap-4"><span>{criterion}</span><span className="text-indigo-700">{scores[criterion] ?? 80}/100</span></div><input aria-label={`${criterion} score`} type="range" min="0" max="100" value={scores[criterion] ?? 80} onChange={event => setScores({ ...scores, [criterion]: Number(event.target.value) })} className="mt-3 w-full accent-indigo-600" /></label>)}</div><div className="mt-6 rounded-lg border p-4"><p className="text-sm text-slate-500">Reference grade</p><p className="mt-1 text-2xl font-bold text-indigo-700">{grade(average)} <span className="text-base font-normal text-slate-500">({average}/100)</span></p><p className="mt-1 text-xs text-slate-500">Informational only; it does not calculate or limit the requested increase.</p></div><label className="mt-6 block text-sm font-medium">Requested salary increase %<input required type="number" min="0" step="0.1" value={increase} onChange={event => setIncrease(Number(event.target.value))} className="mt-2 w-full rounded-lg border p-3" /></label><label className="mt-6 block text-sm font-medium">Comments <textarea value={comments} onChange={event => setComments(event.target.value)} rows={4} className="mt-2 w-full rounded-lg border p-3" placeholder="Optional context for the manager and HR" /></label>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={submitting} className="mt-6 w-full rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white hover:bg-slate-700 disabled:opacity-50">{submitting ? "Submitting…" : "Submit evaluation"}</button><p className="mt-4 text-center text-xs text-slate-400">Once submitted, your score and percentage cannot be edited.</p></form></div></main>;
}
